version: '3.4'

services:
  py-oatmealbot:
    image: oatmealbot
    container_name: bot
    build:
      context: ./oatmealbot
      dockerfile: ./Dockerfile
    command: pipenv run python -m oatmealbot.bot
    env_file:
      - .env
    environment:
      MONGODB_URI: "mongodb://${MONGO_USER}:${MONGO_PASS}@mongo/"
  py-oatmealapi:
    image: oatmealbot
    container_name: api
    build:
      context: ./oatmealbot
      dockerfile: ./Dockerfile
    command: pipenv run python -m uvicorn oatmealbot.api:app --host 0.0.0.0
    ports:
      - "8005:8000"
    env_file:
      - .env
    environment:
      MONGODB_URI: "mongodb://${MONGO_USER}:${MONGO_PASS}@mongo/"
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASS}"
