version: '3.4'

services:
  py-oatmealbot:
    image: py-oatmealbot
    container_name: bot
    build:
      context: ./bot
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment:
      MONGODB_URI: "mongodb://${MONGO_USER}:${MONGO_PASS}@mongo:27017/"
  py-oatmealapi:
    image: py-oatmealapi
    container_name: api
    build:
      context: ./api
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment:
      MONGODB_URI: "mongodb://${MONGO_USER}:${MONGO_PASS}@mongo:27017/"
  # mongo:
  #   image: mongo:latest
  #   container_name: mongo
  #   ports:
  #     - "27018:27017"
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: MONGO_USER
  #     MONGO_INITDB_ROOT_PASSWORD: MONGO_PASS
